### ISSUE TITLE
cannot load modelstate

### ISSUE THREAD

**Issue by liuguicen** [Aaditya-Singh/SAFIN#1]
RuntimeError: Error(s) in loading state_dict for WaveDecoder:
	While copying the parameter named "recon_block3.LL.weight", whose dimensions in the model are torch.Size([256, 1, 2, 2]) and whose dimensions in the checkpoint are torch.Size([256, 1, 2, 2]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).

**Comment by Aaditya-Singh** [comment]
I have updated test.py to address the issue of loading state_dict for the SAFIN modules, but I didn't get any error for the WaveDecoder. As far as I know, this could be an issue due to a disparity in package versions. I would recommend creating a fresh anaconda environment and then installing the requirements to avoid any conflicts.

**Comment by andorxornot** [comment]
yeah,i have this error too. seeems we need older pytorch

**Comment by liuguicen** [comment]
Thank you I try it.

**Comment by LiuXiaolong19920720** [comment]
Same problem， pytorch1.8,  fixed by changing `util.py  get_wav()` function's last four lines:
```python
    LL.weight.data = filter_LL.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
    LH.weight.data = filter_LH.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
    HL.weight.data = filter_HL.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
    HH.weight.data = filter_HH.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
```
to
```python
    LL.weight.data = filter_LL.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
    LH.weight.data = filter_LH.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
    HL.weight.data = filter_HL.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
    HH.weight.data = filter_HH.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
```

**Comment by Rorschach-xyz** [comment]
> Same problem， pytorch1.8, fixed by changing `util.py get_wav()` function's last four lines:
> 
> ```python
>     LL.weight.data = filter_LL.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
>     LH.weight.data = filter_LH.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
>     HL.weight.data = filter_HL.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
>     HH.weight.data = filter_HH.float().unsqueeze(0).expand(in_channels, -1, -1, -1)
> ```
> 
> to
> 
> ```python
>     LL.weight.data = filter_LL.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
>     LH.weight.data = filter_LH.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
>     HL.weight.data = filter_HL.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
>     HH.weight.data = filter_HH.float().unsqueeze(0).expand(in_channels, -1, -1, -1).clone()
> ```
有用感谢
