### ISSUE TITLE
VGG19

### ISSUE THREAD

**Issue by mzprose** [Aaditya-Singh/SAFIN#2]
Have you tried the generation effect of vgg19 encoder decoder + SAFIN?

**Comment by Aaditya-Singh** [comment]
In our initial set of experiments, we tried different architecture variants including VGG-19 with SAFIN. However, the use of Wavelet Transform provides better reconstruction and lesser artifacts without the use of additional loss terms as in [SANet](https://openaccess.thecvf.com/content_CVPR_2019/html/Park_Arbitrary_Style_Transfer_With_Style-Attentional_Networks_CVPR_2019_paper.html).

**Comment by mzprose** [comment]
Thanks for the reply！
