### ISSUE TITLE
'Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for WaveDecoder:

### ISSUE THREAD

**Issue by lyfv1** [Aaditya-Singh/SAFIN#4]
'Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for WaveDecoder:

hello there are some errors？can you help me thanks!

**Comment by Aaditya-Singh** [comment]
Unfortunately, I don't get this error when testing. However, I would recommend you to pull the latest commit and refer to this thread for reference as it might be helpful: https://github.com/Aaditya-Singh/SAFIN/issues/1

**Comment by lyfv1** [comment]
Thanks

**Comment by Zerua-bit** [comment]
> 'Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for WaveDecoder:
> 
> hello there are some errors？can you help me thanks!

Have you resolved this issue?

**Comment by Aaditya-Singh** [comment]
@Zerua-bit I tested again recently and while I didn't run into this error, I found that the latest Python versions do not support torch 1.2 which is needed for this project. Please try creating a new environment with Python 3.7 and install the requirements again, as per the [updated instructions](https://github.com/Aaditya-Singh/SAFIN/tree/main?tab=readme-ov-file#requirements) in the readme. Thanks for your interest!

**Comment by Zerua-bit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
