### ISSUE TITLE
Hi,ask a question about wavepooling

### ISSUE THREAD

**Issue by meiguoofa** [Aaditya-Singh/SAFIN#8]
when i changed the kernel size of the wavepooling, the result of the output of the wavepooling remains the same, it's right?

**Comment by Aaditya-Singh** [comment]
Wavelet pooling is a form of [2d convolution](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html#torch.nn.Conv2d) with fixed weights whose output dimension changes with the kernel size.

**Comment by meiguoofa** [comment]
Thanks for your reply!
